name: SpigotSteve
version: '${version}'
main: org.steve.spigotsteve.SpigotSteve
api-version: '1.20'
commands:
  spigotSteve:
    description: GameRules to customize drop randomization.
    usage: /<spigotSteve> <rule> <true/false>

